#!/usr/bin/env ruby
# frozen_string_literal: true
lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib)

require 'app'

#
# ::main::
#
::App::Cli.run(
  command: Choice[:command],
  arguments: Choice[:arguments]
)
